name: Update README with Recent Activity

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with Recent Activity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Update Recent Activity
        uses: actions-cool/readme-box@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Add this line if you want to specify where to update your README
          file-path: 'README.md'
          box: '<!--START_SECTION:activity-->'
          content: |
            <!-- You can put custom activity message here -->
            - `{{event}}` - {{repo}} {{branch}} - {{actor}} {{message}} - {{time}}

      - name: Commit & Push if Changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update recent activity" || exit 0
          git push origin HEAD
